### ISSUE TITLE
Automatic switching does not work

### ISSUE THREAD

**Issue by fenhl** [paysonwallach/auto-dark-mode#3]
The package doesn't do anything when the system switches between light and dark mode on macOS Sierra. Only the manual hotkey does anything.

**Comment by paysonwallach** [comment]
Unfortunately, I don't believe that apps receive notification of changes to the system's appearance pre-Mojave.

**Comment by fenhl** [comment]
That's unfortunate. Perhaps a fallback system could be added that checks the current mode every n seconds?

**Comment by fenhl** [comment]
In Mojave, the automatic option seems to randomly switch between light and dark mode.

**Comment by dpo** [comment]
FWIW It works for me on 10.14.6 with Atom 1.40.1.

**Comment by fenhl** [comment]
Can confirm, probably fixed in ae7d817669ce0ce51a63f2d102d026b4bc60e47b.
