### ISSUE TITLE
Unable to switch to dark theme automatically

### ISSUE THREAD

**Issue by mikehu98** [paysonwallach/auto-dark-mode#5]
I am currently on macOS 10.15.2 and Atom 1.42.0. It used to work perfectly but at some point, it failed to switch to dark theme automatically although switching to light theme works fine. I'm still able to manually toggle between them. Could this have been a compatibility issue?

**Comment by paysonwallach** [comment]
Thank you for filing the issue. I've only experienced this once myself, and I haven't been able to reproduce it reliably. Do you have any additional information that could assist in this?
