### ISSUE TITLE
Restart required

### ISSUE THREAD

**Issue by jneuendorf** [paysonwallach/auto-dark-mode#6]
Hi,

@paysonwallach First of all: Thanks for this awesome package! 😁 

I had to restart Atom in order to be able to see the package's settings button the list of installed packages in the Atom settings view.

Maybe that should be noted in the README because I was looking through the code before trying to restart. Other people might just be wondering why it "isn't working correctly" after installation.

**Comment by paysonwallach** [comment]
Hi, 

Thank you, I'm glad you like it! I'm sorry you had trouble with the installation. Unfortunately, I haven't been able to recreate the issue. What versions of Atom and macOS are you using?

**Comment by jneuendorf** [comment]
Hi,

thanks for the quick response.

Sorry, I didn't mention my versions 🤦 😄 

macOS: 10.15.3
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.17
git 2.26.0

I am also quite familiar with Atom and I was surprised I had to restart the editor (not sure if a `Window: Reload` would have sufficed...). Maybe it was a one-timer, who knows. Also I didn't do any more testing (on reproducing the behavior) like installing it on a fresh copy of Atom - mine might be screwed up to much 🤷 . 

If you can't reproduce it, feel free to close the issue. If it happens to other people, at least some if them will leave a comment I guess. 😉

**Comment by jltml** [comment]
I know this is an old issue, but I had to restart as well (no big deal or anything!). I installed from the command line with `apm`, so maybe that has to do with it somehow. Anyway, thanks for the super helpful extension!
