### ISSUE TITLE
Atom Theme Doesn't Switch To macOS Theme After Shutdown-Startup

### ISSUE THREAD

**Issue by lifeisbard** [paysonwallach/auto-dark-mode#8]
Hello!

I like your plugin. Thanks for making it.

If I shut down my Mac at night while macOS and Atom are in **dark mode**, then start my Mac up in the morning, the system will have switched to **light mode** while Atom's theme remains in dark mode. I can manually toggle Atom's theme to light mode for the afternoon by using the shortcut key. Then, later when the macOS system theme switches to dark mode at night, Atom's theme will auto-switch to dark mode as expected. However, when I shut down my Mac, then start it up during the morning, Atom starts up in dark mode despite macOS having switched to light mode.

My expectation is that upon having shutdown at night, then starting up during the morning, that **auto-dark-mode** will switch Atom's theme to match the macOS light mode theme (which it does not).

- **OS**: macOS Big Sur 11.0.1
- **Atom**: 1.53.0
- **auto-dark-mode**: 0.5.1

Thanks for your attention.

**Comment by leec-666** [comment]
Here's a quick fix: 

1. Select the package in Atom and select **View Code**
2. Open `lib/main.js`
3. Scroll down to the [`activate` function (59)](https://github.com/paysonwallach/auto-dark-mode/blob/master/lib/main.js#L59)
4. Above the [`window.matchMedia("(prefers-color-scheme: dark)").addListener(e => {` line (64)](https://github.com/paysonwallach/auto-dark-mode/blob/master/lib/main.js#L64), insert the following:
```   
  setTimeout(() => {
    if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
      this.changeTheme(this.darkTheme());
    }
    else this.changeTheme(this.lightTheme());
  }, 50);
```
5. Toggle theme to the wrong one (**Ctrl+`**), restart and test
