### ISSUE TITLE
Switch Modes on fresh start of Atom

### ISSUE THREAD

**Issue by dersimn** [paysonwallach/auto-dark-mode#9]
I'm not sure if this is a bug or a missing feature, but Atom doesn't switch themes on start.

Let's say I closed Atom with the Light theme and start it again after switching the system mode to dark (using macOS 11.0.1). It boots up and stays on the light theme (or anything else that was the state when I closed it in the first place).

Switching only takes place while Atom is running. Is this the intended behaviour?

**Comment by osdouglas** [comment]
Seeing the same behavior

**Comment by leec-666** [comment]
Here's a quick fix: 

1. Select the package in Atom and select **View Code**
2. Open `lib/main.js`
3. Scroll down to the [`activate` function (59)](https://github.com/paysonwallach/auto-dark-mode/blob/master/lib/main.js#L59)
4. Above the [`window.matchMedia("(prefers-color-scheme: dark)").addListener(e => {` line (64)](https://github.com/paysonwallach/auto-dark-mode/blob/master/lib/main.js#L64), insert the following:
```   
  setTimeout(() => {
    if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
      this.changeTheme(this.darkTheme());
    }
    else this.changeTheme(this.lightTheme());
  }, 50);
```
5. Toggle theme to the wrong one (**Ctrl+`**), restart and test

**Comment by femto-code** [comment]
Thanks @chonty - works very well!

I had a look on your PR and it seems pretty applicable - I think the match media part was just forgotten.

Hope that dev @paysonwallach will merge it and publish a new release soon.
